Update encoding examples
LoyaltyNZ/hoodoo pull request #287
Opened 2020-11-10 01:50 UTC by kasperite

2020-11-10 02:34 UTC, pond requested changes

2020-11-10 02:34 UTC, davidoram reviewed
Is there any way to verify the behavior is correct (and the comments are wrong)via a spec?

2020-11-10 02:34 UTC, pond commented on docs/api_specification/README.md
> +  `offset=75&limit=25&sort=name&direction=asc&search=name%3Dstr%253Fange%253Dvalue%26address%252Cstreet%3D11%2BCable%2BStreet`
The idea of the old example was to specifically demonstrate that double-encoding is necessary, which is why it uses `%20` rather than `+`. If you do want to use `+` instead, please add in some other character where the docs demonstrate `%25XX` encoding and make sure that line 278 above has the right description - presently, it still says:

> ...the escaped values to search for become `str%3Fange%3Dvalue` and `11%20Cable%20Street`...

2020-11-10 02:36 UTC, pond commented
Hi @daveoram :-) long time no write. There is nothing wrong with the documentation either before or after (except for that oversight on the update to line 278 and the updated docs not really demonstrating what that section is intended to demonstrate); the encoding is correct either way. It's been a while, but I'm pretty sure that waaaaay back in the day, I did add test coverage for double encoding.

2020-11-10 02:37 UTC, davidoram commented
Nice to hear from you @pond . Hope things are well with you.

2020-11-10 02:39 UTC, pond commented
@davidoram Yeah likewise :-)

2020-11-10 21:32 UTC, kasperite commented on docs/api_specification/README.md
> +  `offset=75&limit=25&sort=name&direction=asc&search=name%3Dstr%253Fange%253Dvalue%26address%252Cstreet%3D11%2BCable%2BStreet`
> The idea of the old example was to specifically demonstrate that double-encoding is necessary, which is why it uses `%20` rather than `+`. If you do want to use `+` instead, please add in some other character where the docs demonstrate `%25XX` encoding and make sure that line 278 above has the right description - presently, it still says:
> 
> > ...the escaped values to search for become `str%3Fange%3Dvalue` and `11%20Cable%20Street`...

hey @pond , I've updated README to include encoding datetime(using https://github.com/LoyaltyNZ/hoodoo/blob/ece404fa705e1d5965605bc6f517bee41dbca396/docs/api_specification/README.md#craftcrbef as example)

2020-11-10 21:45 UTC, kasperite commented on docs/api_specification/README.md
> +  `offset=75&limit=25&sort=name&direction=asc&search=name%3Dstr%253Fange%253Dvalue%26address%252Cstreet%3D11%2BCable%2BStreet`
you are right, escaped space can be either `%20` or `+` depending on whether it's the output of `URI.escape` or `CGI.escape`.

2020-11-10 23:09 UTC, pond commented on docs/api_specification/README.md
> +  `offset=75&limit=25&sort=name&direction=asc&search=name%3Dstr%253Fange%253Dvalue%26address%252Cstreet%3D11%2BCable%2BStreet`
@kasperite That's intense 😂 but does definitely show double encoding, so all good for me; you've still got some Travis issues by the looks of it, but otherwise I'm happy.

2020-11-10 23:10 UTC, pond approved these changes
All good now, once whatever's up with Travis is sorted anyway.

2020-11-10 23:14 UTC, davidoram approved these changes
Approved pending fix to travis tests

2020-11-11 04:15 UTC, kasperite commented
@pond @davidoram I had to update rack due to bundle audit and it turns out newer rack returns response body abit differently.  

FYI:
https://www.rubydoc.info/gems/rack/2.0.8/Rack%2FResponse:finish - current rack 2.0.8. `body` is wrapped in `BodyProxy`
https://www.rubydoc.info/gems/rack/Rack%2FResponse:finish - latest rack 2.2.3. No wrapping

2020-11-11 20:12 UTC, merged